# Generated by Django 2.2.19 on 2022-01-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dod_asset1_dod_asset2_dod_asset3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dod_asset1',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dod_asset1',
            name='name',
        ),
        migrations.AddField(
            model_name='dod_asset1',
            name='pilot',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
